### ISSUE TITLE
README link to figma plugin throws 404

### ISSUE THREAD

**Issue by emcee3** [bridgedxyz/figma#2]
**Describe the bug**
README link to figma plugin throws 404.

**To Reproduce**
1. Go to 'README'
2. Click on 'First link'

**Expected behavior**
The link goes somewhere. 

**Screenshots**
![](https://i.imgur.com/ajiBowZ.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by softmarshmallow** [comment]
@emcee3  the plugin is under review by figma team. after the review is complete, it will be available publicly.

I can see the link (since i'm the owner)

Please run the plugin via clone & run.

Thanks for the report!

**Comment by softmarshmallow** [comment]
#10  plugin is now published.@emcee3
